# Generated by Django 4.2.3 on 2023-07-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_author_alter_posts_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="posts",
            old_name="post",
            new_name="post_body",
        ),
        migrations.AddField(
            model_name="posts",
            name="post_title",
            field=models.CharField(default="My Title", max_length=20),
            preserve_default=False,
        ),
    ]
