# Generated by Django 4.2.3 on 2023-07-19 20:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_rename_post_posts_post_body_posts_post_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="posts",
            name="published_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="posts",
            name="updated_at",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
