# Generated by Django 4.2.3 on 2023-07-25 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_posts_published_at_posts_updated_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
