# Generated by Django 4.2.3 on 2023-09-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_post_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_title",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
