# Generated by Django 4.2.3 on 2023-11-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_alter_post_post_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="post_preview",
            field=models.TextField(
                default=models.CharField(max_length=100, unique=True)
            ),
        ),
    ]
